### ISSUE TITLE
Rethink the `*` wildcard

### ISSUE THREAD

**Issue by waldyrious** [uphold/anonymizer#18]
Extracted from #16 by @Americas:

> The current behavior for * in the regexp is `.*`, this effectively whitelists any character, including the `.` that is used to delimit paths.

> This means that currently `*.foo` of `foo.*` would match:
>
> ```
> *.foo
>
> .foo
> a.foo
> a.b.foo
> a.b.c.foo
> ...
> ```
>
> ```
> foo.*
>
> foo.
> foo.a
> foo.a.b
> foo.a.b.c
> ...
> ```

> If this is truly expected behavior, we should think about adding the `**` pattern to match multiple paths.

**Comment by Americas** [comment]
Seems like it was finally "discussed" and changed on #38 :tada:
